### ISSUE TITLE
num_pages

### ISSUE THREAD

**Issue by mgermy** [GeovRodri/zapimoveis-scraper#2]
For some reason, when I select `num_pages`, the second-page results are a copy of the first one. I found it out when I was calculating the average for the and it did not change regardless of how many pages I chose. I've been trying to find out where this problem is, but no success so far 😕

**Comment by GeovRodri** [comment]
Resolved in https://github.com/GeovRodri/zapimoveis-scraper/commit/dac25f52ef0112b75de9f878c938606c128fbad3
