### ISSUE TITLE
Duvida em como Usar a Biblioteca

### ISSUE THREAD

**Issue by luihzpg** [GeovRodri/zapimoveis-scraper#4]
Olá 

Parabens pelo trabalho.

Estou com a seguinte dificuldade

import zapimoveis_scraper
z=zapimoveis_scraper.search(localization='mg+belo-horizonte++luxemburgo', num_pages=5)

Apos gerar o objeco "z" como faço para visualizar e exportador os dados para o Pandas por exemplo?

Obrigado!

**Comment by GeovRodri** [comment]
Olá, me desculpa pela demora para responder.

Você pode transformar tudo em dicionário, utilizando o __dict__.
Um exemplo de código aí para você fazer isso:
``` 
    items = []
    for item in search(**params):
        items.append(item.__dict__)
```

Aí o seu items será uma lista de dicionários, acredito que dessa forma você já cria seu DataFrame:
```
   df = pd.DataFrame(items)
``` 

Se der certo dê o feedback para a gente, para caso outras pessoas apareçam com a mesma dúvida.

**Comment by 5nilha** [comment]
Olá,

Muito legal o trabalho de vocês. Eu utilizei e gostei muito, entretanto, estou com uma dúvida. Quando retorna o resultado da pesquisa, existe alguma forma de conseguir o link da pagina de cada propriedade?

**Comment by GeovRodri** [comment]
Olá @5nilha,
Atualmente não temos essa funcionalidade 😞 . Atualmente não estou podendo implementar essa funcionalidade, caso alguém queira implementar será bem vindo o pull requests.

**Comment by brunolelli** [comment]
É possível filtrar pelo tipo: "salão, comercial..."?
Tem como filtrar por Comprar ou Alugar?

Obrigado

**Comment by GeovRodri** [comment]
Olá @5nilha, agora é possível pegar os links de cada propriedade, graças ao @LinkForce
