### ISSUE TITLE
Erro ao indicar acao='venda'

### ISSUE THREAD

**Issue by P3droCWB** [GeovRodri/zapimoveis-scraper#7]
Olá, 

em primeiro lugar quero dizer que achei muito bacana projeto. Sou estudante de computação e estou estudando python no momento. 

Bem, tentei usar o zapimoveis_scraper para trazer os imóveis a venda em Curitiba:
result = zap.search(localization="pr+curitiba", num_pages=5, acao='venda')

E o erro a seguir ocorreu:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-395a4ffe7e98> in <module>
----> 1 result = zap.search(localization="pr+curitiba", num_pages=5, acao='venda')

~\AppData\Local\Programs\Python\Python39\lib\site-packages\zapimoveis_scraper\__init__.py in search(localization, num_pages, acao, tipo, dictionary_out)
    122         for listing in listings:
    123             if 'type' not in listing or listing['type'] != 'nearby':
--> 124                 items.append(get_ZapItem(listing))
    125 
    126         page += 1

~\AppData\Local\Programs\Python\Python39\lib\site-packages\zapimoveis_scraper\__init__.py in get_ZapItem(listing)
     99     item = ZapItem()
    100     item.link = listing['link']['href']
--> 101     item.price = listing['listing']['pricingInfos'][0]['price']
    102     item.bedrooms = listing['listing']['bedrooms'][0] if len(listing['listing']['bedrooms']) > 0 else 0
    103     item.bathrooms = listing['listing']['bathrooms'][0] if len(listing['listing']['bathrooms']) > 0 else 0

KeyError: 'price'

Estou usando **zapimoveis_scraper** de maneira errada?

**Comment by GeovRodri** [comment]
Olá, boa tarde. Tinha um erro aí mesmo, muito obrigado por avisar.

Acabei de subir uma nova versão com a correção disso aí, atualize a versão do zapimoveis_scraper ```pip install zapimoveis_scraper --upgrade``` que vai dar certo.

**Comment by P3droCWB** [comment]
Obrigado!
